"use client";

import Link from "next/link";
import { ArrowLeft, ClipboardList, FileCheck2, Ship } from "lucide-react";

import { MatchResultCard } from "@/components/match-result-card";
import { StatusBadge } from "@/components/status-badge";
import { useAuth } from "@/components/auth/auth-provider";
import {
  BuyerIntroductionForm,
  CommercialTermsForm,
  CommissionForm,
  InspectionForm,
  NegotiationRoundForm,
  PaymentMilestoneForm,
  ShipmentForm,
} from "@/components/deals/deal-workflow-forms";
import { useSupplierWorkspace } from "@/lib/data/use-supplier-workspace";
import { updateDealPaymentMilestone, updateDealShipment, updateDealStage } from "@/lib/data/supplier-workspace";
import { can } from "@/lib/auth/permissions";
import { buyerRequirements } from "@/lib/data/demo-data";
import { DEAL_STATUSES } from "@/lib/domain/deal";
import type { DealPaymentMilestone, DealShipment } from "@/lib/domain/deal-workflow";
import { matchMineralProduct, productWithAssay } from "@/lib/matching";
import { calculateDealValue, calculateEstimatedCommission } from "@/lib/utils/commercial-math";

const numberFormatter = new Intl.NumberFormat("en-US");
const dateFormatter = new Intl.DateTimeFormat("en-GB", { timeZone: "UTC", day: "numeric", month: "short", year: "numeric" });
const labelFor = (value: string) => value.replaceAll("_", " ");

function DealActivityTimeline({ events }: { events: { id: string; title: string; details: string; createdAt: string; actorName?: string }[] }) {
  return <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">Deal activity</h2><div className="mt-3 divide-y divide-slate-100">{events.length ? events.map((event) => <div key={event.id} className="py-3"><div className="flex flex-wrap justify-between gap-2"><span className="text-sm font-medium text-slate-900">{event.title}</span><time className="text-xs text-slate-500">{dateFormatter.format(new Date(event.createdAt))} UTC</time></div><p className="mt-1 text-xs text-slate-600">{event.details}</p><p className="mt-1 text-[10px] text-slate-500">Actor: {event.actorName ?? "System / development fixture"}</p></div>) : <p className="py-3 text-sm text-slate-500">No deal events recorded.</p>}</div></section>;
}

function ComparisonRow({ label, requirement, offer, status }: { label: string; requirement: string; offer: string; status: string }) {
  return <div className="grid gap-2 border-b border-slate-100 py-2 text-xs sm:grid-cols-[minmax(100px,0.7fr)_1fr_1fr_100px] sm:items-center"><span className="font-semibold text-slate-800">{label}</span><span className="text-slate-600">Requirement: {requirement}</span><span className="text-slate-600">Supplier offer: {offer}</span><span className="sm:text-right"><StatusBadge label={status} /></span></div>;
}

function ShipmentCard({ shipment, editable }: { shipment: DealShipment; editable: boolean }) {
  return <article className="rounded-lg border border-slate-200 p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div className="font-medium text-slate-900">{shipment.isDemoFixture ? "Synthetic planned shipment" : "Shipment record"}</div>{editable ? <select aria-label="Shipment status" value={shipment.status} onChange={(event) => updateDealShipment(shipment.id, { status: event.target.value as DealShipment["status"] })} className="h-8 rounded-md border border-slate-300 bg-white px-2 text-xs">{["PLANNED", "READY_FOR_LOADING", "LOADED", "IN_TRANSIT", "ARRIVED", "INSPECTION_PENDING", "COMPLETED", "CANCELLED"].map((status) => <option key={status} value={status}>{labelFor(status)}</option>)}</select> : <StatusBadge label={shipment.status} />}</div><div className="mt-2 grid gap-2 text-xs text-slate-600 sm:grid-cols-3"><span>Planned: {shipment.plannedQuantityMt ?? "Unknown"} MT</span><span>Actual: {shipment.actualQuantityMt ?? "Unknown"} MT</span><span>ETD / ETA: {shipment.etd?.slice(0, 10) ?? "Unknown"} / {shipment.eta?.slice(0, 10) ?? "Unknown"}</span><span>Loading: {shipment.loadingLocation ?? "Unknown"}</span><span>Destination: {shipment.destinationPort ?? "Unknown"}</span><span>Inspection ref: {shipment.inspectionReference ?? "Unknown"}</span><span>B/L ref: {shipment.billOfLadingReference ?? "Unknown"}</span></div>{shipment.notes && <p className="mt-2 text-xs text-slate-600">{shipment.notes}</p>}{shipment.isDemoFixture && <p className="mt-2 text-[10px] font-semibold uppercase text-amber-800">Synthetic example only · no shipment exists</p>}</article>;
}

function PaymentRow({ payment, editable }: { payment: DealPaymentMilestone; editable: boolean }) {
  return <article className="grid gap-2 rounded-lg border border-slate-200 p-3 sm:grid-cols-[minmax(0,1fr)_200px] sm:items-center"><div><div className="font-medium text-slate-900">{payment.milestone}</div><div className="mt-1 text-xs text-slate-600">Expected: {payment.expectedPercentage ?? "Unknown"}% · {payment.currency ?? "Currency unknown"} {payment.expectedAmount ?? "Amount unknown"} · Due {payment.dueDate?.slice(0, 10) ?? "Not set"}</div>{payment.reference && <div className="mt-1 text-xs text-slate-500">Reference: {payment.reference}</div>}{payment.notes && <div className="mt-1 text-xs text-slate-500">{payment.notes}</div>}</div>{editable ? <select aria-label={`${payment.milestone} status`} value={payment.status} onChange={(event) => updateDealPaymentMilestone(payment.id, event.target.value as DealPaymentMilestone["status"])} className="h-9 rounded-md border border-slate-300 bg-white px-2 text-xs">{["NOT_DUE", "DUE", "PENDING", "PAID", "PARTIALLY_PAID", "ADJUSTMENT_REQUIRED", "COMPLETED"].map((status) => <option key={status} value={status}>{labelFor(status)}</option>)}</select> : <StatusBadge label={payment.status} />}</article>;
}

export function DealWorkspace({ dealId }: { dealId: string }) {
  const { user } = useAuth();
  const { workspace, ready } = useSupplierWorkspace();
  const canManageStage = can(user, "deal.stage.manage");
  const canReadCommercial = can(user, "commercial.read");
  const canEditCommercial = can(user, "commercial.edit");
  const canReadCommission = can(user, "commission.read");
  const canEditCommission = can(user, "commission.edit");
  const canReadShipment = can(user, "shipment.read");
  const canManageShipment = can(user, "shipment.manage");
  const canReadPayments = can(user, "payment.read");
  const canManagePayments = can(user, "payment.manage");
  const canIntroduceBuyer = can(user, "deal.introduction.manage");
  const deal = workspace.deals.find((item) => item.id === dealId);
  if (!deal) return <div className="rounded-xl border border-slate-200 bg-white p-6"><p className="text-sm text-slate-600">{ready ? "Deal not found in this browser workspace." : "Loading deal workspace…"}</p><Link href="/deals" className="mt-3 inline-flex items-center gap-2 text-sm font-medium text-emerald-800"><ArrowLeft className="h-4 w-4" /> Back to deals</Link></div>;

  const supplier = workspace.suppliers.find((item) => item.id === deal.supplierId);
  const product = workspace.products[deal.supplierId]?.find((item) => item.id === deal.productId);
  const requirement = buyerRequirements.find((item) => item.id === deal.requirementId);
  const assay = workspace.assays[deal.supplierId]?.filter((item) => item.productId === deal.productId).at(-1);
  const matchingProduct = product && productWithAssay(product, assay);
  const matchResult = workspace.dealMetadata[dealId]?.matchResult ?? (matchingProduct && requirement ? matchMineralProduct(matchingProduct, requirement) : undefined);
  const terms = workspace.commercialTerms[dealId];
  const commission = workspace.commissions[dealId];
  const intro = workspace.buyerIntroductions[dealId];
  const rounds = [...(workspace.negotiationRounds[dealId] ?? [])].sort((left, right) => left.date.localeCompare(right.date) || left.createdAt.localeCompare(right.createdAt));
  const shipments = workspace.shipments.filter((item) => item.dealId === dealId);
  const inspections = workspace.inspections.filter((item) => item.dealId === dealId);
  const payments = workspace.paymentMilestones.filter((item) => item.dealId === dealId);
  const activities = workspace.dealActivities[dealId] ?? [];
  const value = calculateDealValue(terms?.quantityMt, terms?.pricePerMt, terms?.currency);
  const estimatedCommission = calculateEstimatedCommission({ quantityMt: terms?.quantityMt, pricePerMt: terms?.pricePerMt, percentage: commission?.type === "PERCENTAGE" ? commission.percentage : undefined, fixedAmount: commission?.type === "FIXED" ? commission.fixedAmount : undefined, currency: commission?.currency ?? terms?.currency });
  const paymentProgress = payments.reduce((sum, payment) => ["PAID", "COMPLETED"].includes(payment.status) ? sum + (payment.expectedPercentage ?? 0) : sum, 0);
  const trialQuantity = terms?.quantityMt ?? deal.quantityMt ?? product?.trialQuantityMt;
  const hasTrialRange = requirement?.trialQuantityMinMt !== undefined || requirement?.trialQuantityMaxMt !== undefined;
  const trialStatus = trialQuantity === undefined || !hasTrialRange ? "MISSING" : requirement.trialQuantityMinMt !== undefined && trialQuantity < requirement.trialQuantityMinMt || requirement.trialQuantityMaxMt !== undefined && trialQuantity > requirement.trialQuantityMaxMt ? "FAIL" : "PASS";
  const incotermStatus = !terms?.incoterm || !requirement ? "MISSING" : requirement.incoterms.includes(terms.incoterm) ? "COMPATIBLE" : "FAIL";
  const paymentStatus = !terms?.paymentMethod || !requirement ? "MISSING" : requirement.paymentMethods.includes(terms.paymentMethod) ? "COMPATIBLE" : "FAIL";
  const currency = terms?.currency ?? "USD";
  const supplierUnqualified = Boolean(supplier && (supplier.verificationStatus !== "VERIFIED" || supplier.pipelineStatus !== "QUALIFIED"));

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/deals" className="inline-flex items-center gap-2 text-sm font-medium text-slate-600 hover:text-slate-900"><ArrowLeft className="h-4 w-4" /> Back to deals</Link><div className="flex flex-wrap gap-2">{workspace.dealMetadata[dealId]?.isDemoFixture && <StatusBadge label="SYNTHETIC FIXTURE" />}<StatusBadge label={deal.status} /></div></div>
      <header className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><div className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-500">Commercial deal workspace</div><h1 className="mt-2 text-2xl font-semibold text-slate-900">{supplier?.companyName ?? "Unknown supplier"} · {product?.specification.commodity ?? "Unknown commodity"}</h1><p className="mt-2 text-sm text-slate-600">Buyer account {deal.buyerId} · {requirement?.title ?? "Requirement unavailable"} · {workspace.dealMetadata[dealId]?.supplyType ?? "Supply type unknown"}</p></div><label className="text-xs font-medium text-slate-600">Deal stage<select aria-label="Deal stage" disabled={!canManageStage} value={deal.status} onChange={(event) => updateDealStage(dealId, event.target.value as typeof deal.status)} className="mt-1 block h-9 rounded-md border border-slate-300 bg-white px-2 text-sm disabled:bg-slate-100">{DEAL_STATUSES.map((status) => <option key={status} value={status}>{labelFor(status)}</option>)}</select></label></div></header>
      {workspace.dealMetadata[dealId]?.isDemoFixture && <div className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950"><strong>Synthetic development deal.</strong> Values and activity are illustrative fixtures, not genuine offers or transactions.</div>}
      {supplierUnqualified && <div className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950">Supplier qualification is incomplete. Review verification before commercial progression.</div>}

      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        {canReadCommercial && <>
          <div className="rounded-xl border border-slate-200 bg-white p-4"><div className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Quantity</div><div className="mt-2 text-lg font-semibold text-slate-900">{terms?.quantityMt === undefined ? "Unknown" : `${numberFormatter.format(terms.quantityMt)} MT`}</div><StatusBadge label={terms?.valueState ?? "UNKNOWN"} /></div>
          <div className="rounded-xl border border-slate-200 bg-white p-4"><div className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Price / MT</div><div className="mt-2 text-lg font-semibold text-slate-900">{terms?.pricePerMt === undefined ? "Unknown" : `${terms.currency ?? "Currency unknown"} ${terms.pricePerMt}`}</div><StatusBadge label={terms?.valueState ?? "UNKNOWN"} /></div>
          <div className="rounded-xl border border-sky-200 bg-sky-50 p-4"><div className="text-[10px] font-semibold uppercase tracking-wide text-sky-800">Deal value · {terms?.valueState ?? "INDICATIVE"}</div><div className="mt-2 text-lg font-semibold text-slate-900">{value ?? "Unknown"}</div><div className="mt-1 text-[10px] uppercase text-sky-800">{terms?.valueState === "ACTUAL" ? "Recorded actual value" : terms?.valueState === "AGREED" ? "Agreed terms · not actual" : "Indicative · not finalized"}</div></div>
        </>}
        {canReadCommission && <div className="rounded-xl border border-amber-300 bg-amber-50 p-4"><div className="text-[10px] font-semibold uppercase tracking-wide text-amber-900">Estimated commission</div><div className="mt-2 text-lg font-semibold text-slate-900">{estimatedCommission ?? "Unknown"}</div><div className="mt-1 text-[10px] uppercase text-amber-900">Estimate · {commission?.status ?? "NOT AGREED"} · not revenue</div></div>}
        {!canReadCommercial && !canReadCommission && <p className="rounded-xl border border-slate-200 bg-white p-4 text-sm text-slate-600">Commercial and commission values are restricted for your role.</p>}
      </section>

      <div className="grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(300px,0.65fr)]">
        <div className="space-y-5">
          <section className="rounded-xl border border-slate-200 bg-white p-5"><div className="mb-3 flex items-center gap-2"><ClipboardList className="h-4 w-4 text-slate-500" /><h2 className="font-semibold text-slate-900">Requirement & match</h2></div>{requirement ? <div className="mb-4 grid gap-2 text-xs sm:grid-cols-3"><div className="rounded-md bg-slate-50 p-3"><div className="text-slate-500">Buyer requirement</div><div className="mt-1 font-semibold text-slate-900">{requirement.title}</div></div><div className="rounded-md bg-slate-50 p-3"><div className="text-slate-500">Commodity / type</div><div className="mt-1 font-semibold text-slate-900">{requirement.commodity} · {requirement.productType}</div></div><div className="rounded-md bg-slate-50 p-3"><div className="text-slate-500">Destination</div><div className="mt-1 font-semibold text-slate-900">{requirement.destinationCountry}</div></div></div> : <p className="text-sm text-slate-500">Linked buyer requirement is unavailable.</p>}{matchResult && supplier && <><MatchResultCard supplierName={supplier.companyName} result={matchResult} /><p className="mt-2 text-xs text-slate-500">Match evidence: {workspace.dealMetadata[dealId]?.matchEvidenceSource ?? (assay ? `${assay.source} assay` : "Supplier-provided product specification")}. A match is not verification or qualification.</p></>}
            <div className="mt-4 border-t border-slate-200 pt-3"><h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500">Commercial / specification comparison</h3>{requirement && <div><ComparisonRow label="Monthly capacity" requirement={`≥ ${numberFormatter.format(requirement.monthlyQuantityMt)} MT`} offer={product?.monthlyCapacityMt === undefined ? "Not provided" : `${numberFormatter.format(product.monthlyCapacityMt)} MT`} status={product?.monthlyCapacityMt === undefined ? "MISSING" : product.monthlyCapacityMt >= requirement.monthlyQuantityMt ? "PASS" : "FAIL"} /><ComparisonRow label="Trial quantity" requirement={`${requirement.trialQuantityMinMt ?? "Unknown"}–${requirement.trialQuantityMaxMt ?? "Unknown"} MT`} offer={trialQuantity === undefined ? "Not provided" : `${numberFormatter.format(trialQuantity)} MT`} status={trialStatus} />{canReadCommercial && <><ComparisonRow label="Incoterm" requirement={requirement.incoterms.join(" / ")} offer={terms?.incoterm ?? "Unknown"} status={incotermStatus} /><ComparisonRow label="Payment" requirement={requirement.paymentMethods.map((method) => method === "TT" ? "T/T" : method).join(" / ")} offer={terms?.paymentMethod === "TT" ? "T/T" : terms?.paymentMethod ?? "Unknown"} status={paymentStatus} /></>}<ComparisonRow label="Destination" requirement={requirement.destinationCountry} offer={workspace.dealMetadata[dealId]?.destination ?? (canReadCommercial ? terms?.destinationPort : undefined) ?? "Unknown"} status={workspace.dealMetadata[dealId]?.destination || (canReadCommercial && terms?.destinationPort) ? "RECORDED" : "MISSING"} /></div>}</div>
          </section>

          <section className="rounded-xl border border-slate-200 bg-white p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-slate-900">Commercial terms</h2><p className="mt-1 text-xs text-slate-500">Unknown values remain unset; supplier-provided terms are not buyer acceptance.</p></div>{canReadCommercial && <StatusBadge label={terms?.valueState ?? "INDICATIVE"} />}</div>{!canReadCommercial ? <p className="text-sm text-slate-600">Commercial terms are restricted for your role.</p> : canEditCommercial ? <CommercialTermsForm key={`${dealId}-${terms?.updatedAt ?? "empty"}`} dealId={dealId} current={terms} /> : <dl className="grid gap-3 text-sm sm:grid-cols-2">{[["Quantity", terms?.quantityMt === undefined ? "Unknown" : `${terms.quantityMt} MT`], ["Price / MT", terms?.pricePerMt === undefined ? "Unknown" : `${terms.currency ?? "Unknown currency"} ${terms.pricePerMt}`], ["Incoterm", terms?.incoterm ?? "Unknown"], ["Payment", terms?.paymentMethod === "TT" ? "T/T" : terms?.paymentMethod ?? "Unknown"], ["Destination port", terms?.destinationPort ?? "Unknown"], ["Value state", terms?.valueState ?? "Unknown"]].map(([label, value]) => <div key={label}><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 font-medium text-slate-900">{value}</dd></div>)}</dl>}</section>

          <section className="rounded-xl border border-slate-200 bg-white p-5"><div className="mb-3 flex items-center gap-2"><FileCheck2 className="h-4 w-4 text-slate-500" /><div><h2 className="font-semibold text-slate-900">Buyer introduction</h2><p className="mt-1 text-xs text-slate-500">{intro ? "Introduced" : "Not Introduced"} · Match does not imply introduction.</p></div></div>{intro ? <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm"><div className="font-semibold text-slate-900">Introduction explicitly recorded · {intro.introducedAt.slice(0, 10)}</div><div className="mt-1 text-xs text-slate-700">Supplier contact: {supplier?.contacts.find((contact) => contact.id === intro.supplierContactId)?.name ?? "Unknown"} · Buyer contact: {intro.buyerContactName ?? "Unknown"} · Introduced by: {intro.introducedBy}</div>{intro.internalNotes && <p className="mt-2 text-xs text-slate-600">{intro.internalNotes}</p>}</div> : canIntroduceBuyer ? <BuyerIntroductionForm dealId={dealId} requirementId={deal.requirementId} supplierContacts={supplier?.contacts.map((contact) => ({ id: contact.id, name: contact.name })) ?? []} /> : <p className="text-sm text-slate-600">Recording introductions is restricted for your role.</p>}</section>

          {canReadCommercial && <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">Negotiation history</h2><p className="mt-1 text-xs text-slate-500">Rounds are append-only records and displayed chronologically.</p><div className="mt-3 space-y-2">{rounds.length ? rounds.map((round, index) => <article key={round.id} className="rounded-lg border border-slate-200 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-semibold text-slate-900">Round {index + 1} · {labelFor(round.party)}</h3><time className="text-xs text-slate-500">{round.date.slice(0, 10)}</time></div><div className="mt-2 grid gap-2 text-xs text-slate-700 sm:grid-cols-3"><span>Quantity: {round.quantityMt ?? "Unknown"} MT</span><span>Price: {round.currency ?? "Currency unknown"} {round.pricePerMt ?? "Unknown"} / MT</span><span>Incoterm: {round.incoterm ?? "Unknown"}</span><span>Payment: {round.paymentMethod === "TT" ? "T/T" : round.paymentMethod ?? "Unknown"} · {round.paymentTerms ?? "Terms unknown"}</span><span>Destination: {round.destination ?? "Unknown"}</span></div>{round.comments && <p className="mt-2 text-xs text-slate-600">{round.comments}</p>}</article>) : <p className="text-sm text-slate-500">No negotiation rounds. Initial terms are not negotiation history.</p>}</div>{canEditCommercial && <details className="mt-4"><summary className="cursor-pointer text-sm font-semibold text-emerald-800">Add negotiation round</summary><div className="mt-3 rounded-lg bg-slate-50 p-4"><NegotiationRoundForm dealId={dealId} destination={workspace.dealMetadata[dealId]?.destination} /></div></details>}</section>}

          {canReadShipment && <section className="rounded-xl border border-slate-200 bg-white p-5"><div className="mb-3 flex items-center gap-2"><Ship className="h-4 w-4 text-slate-500" /><h2 className="font-semibold text-slate-900">Trial shipment</h2></div><p className="mb-3 text-xs text-slate-500">Inspection milestones are separate from supplier assays. Planned/actual shipment fields remain unknown unless entered.</p><div className="space-y-3">{shipments.length ? shipments.map((shipment) => <ShipmentCard key={shipment.id} shipment={shipment} editable={canManageShipment} />) : <p className="text-sm text-slate-500">No shipment records. Deal stage alone does not establish a shipment.</p>}</div>{canManageShipment && <details className="mt-4"><summary className="cursor-pointer text-sm font-semibold text-emerald-800">Create shipment record</summary><div className="mt-3 rounded-lg bg-slate-50 p-4"><ShipmentForm dealId={dealId} /></div></details>}</section>}

          {canReadShipment && <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">Inspection milestones</h2><p className="mt-1 text-xs text-slate-500">Loading-port and arrival/final inspection remain independent of assay records.</p><div className="mt-3 space-y-2">{inspections.length ? inspections.map((inspection) => <article key={inspection.id} className="rounded-lg border border-slate-200 p-3 text-xs"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-semibold text-slate-900">{labelFor(inspection.point)} · {inspection.agency}</span><StatusBadge label={inspection.status} /></div><div className="mt-1 text-slate-600">Reference: {inspection.reference ?? "Unknown"} · Date: {inspection.date?.slice(0, 10) ?? "Unknown"}</div>{inspection.resultNotes && <p className="mt-1 text-slate-600">{inspection.resultNotes}</p>}</article>) : <p className="text-sm text-slate-500">No inspection milestones recorded.</p>}</div>{canManageShipment && <details className="mt-4"><summary className="cursor-pointer text-sm font-semibold text-emerald-800">Add inspection milestone</summary><div className="mt-3 rounded-lg bg-slate-50 p-4"><InspectionForm dealId={dealId} shipmentId={shipments[0]?.id} /></div></details>}</section>}

          {canReadPayments && <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">Payment milestones</h2><p className="mt-1 text-xs text-slate-500">Operational tracking only. A status is an internal record and does not execute or confirm a bank transfer.</p><div className="mt-3"><div className="mb-3 flex items-center justify-between text-xs"><span className="text-slate-600">Milestones marked paid/completed</span><strong className="text-slate-900">{Math.min(paymentProgress, 100)}%</strong></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-emerald-700" style={{ width: `${Math.min(paymentProgress, 100)}%` }} /></div></div><div className="mt-3 space-y-2">{payments.length ? payments.map((payment) => <PaymentRow key={payment.id} payment={payment} editable={canManagePayments} />) : <p className="text-sm text-slate-500">No payment milestones recorded.</p>}</div>{canManagePayments && <details className="mt-4"><summary className="cursor-pointer text-sm font-semibold text-emerald-800">Add payment milestone</summary><div className="mt-3 rounded-lg bg-slate-50 p-4"><PaymentMilestoneForm dealId={dealId} currency={currency} /></div></details>}</section>}

          <DealActivityTimeline events={activities} />
        </div>

        <aside className="space-y-5">
          <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">Deal overview</h2><dl className="mt-3 space-y-3 text-xs">{[["Buyer", deal.buyerId], ["Requirement", requirement?.title ?? "Unavailable"], ["Supplier", supplier?.companyName ?? "Unavailable"], ["Product", product?.name ?? "Unavailable"], ["Commodity", product?.specification.commodity ?? "Unknown"], ["Product type", product?.specification.productType ?? "Unknown"], ["Supply type", workspace.dealMetadata[dealId]?.supplyType ?? "Unknown"], ["Destination", workspace.dealMetadata[dealId]?.destination ?? terms?.destinationPort ?? "Unknown"]].map(([label, value]) => <div key={label} className="flex justify-between gap-3 border-b border-slate-100 pb-2"><dt className="text-slate-500">{label}</dt><dd className="text-right font-medium text-slate-900">{value}</dd></div>)}</dl>{deal.notes && <p className="mt-3 text-xs text-slate-600">{deal.notes}</p>}</section>
          {canReadCommission && <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">Commission tracking</h2><div className="mt-3 rounded-lg border border-amber-300 bg-amber-50 p-3"><div className="text-[10px] font-semibold uppercase tracking-wide text-amber-900">Estimated commission · not revenue</div><div className="mt-1 text-lg font-semibold text-slate-900">{estimatedCommission ?? "Unknown"}</div><div className="mt-1 text-xs text-slate-700">{commission?.type === "PERCENTAGE" ? `${commission.percentage ?? "Unknown"}%` : commission?.type === "FIXED" ? "Fixed commission" : "Structure unknown"} · Status: {commission?.status ?? "NOT AGREED"}</div><p className="mt-2 text-[11px] text-amber-900">Only explicitly recorded EARNED/INVOICED/PAID statuses represent commission progression. No revenue is recognized here.</p></div>{canEditCommission ? <details className="mt-3"><summary className="cursor-pointer text-sm font-semibold text-emerald-800">Edit commission terms</summary><div className="mt-3"><CommissionForm key={`${dealId}-${commission?.updatedAt ?? "empty"}`} dealId={dealId} current={commission} /></div></details> : <p className="mt-3 text-xs text-slate-500">Commission editing is restricted for your role.</p>}</section>}
        </aside>
      </div>
    </div>
  );
}
